tangxifan/micro_benchmark

simple_registers/counters/counter128_async_reset/counter128_async_reset.v, simple_registers/counters/counter128_async_resetb/counter128_async_resetb.v, simple_registers/counters/counter4_2clock/counter4_2clock.v, simple_registers/counters/counter8_async_reset/counter8_async_reset.v, simple_registers/counters/counter8_async_resetb/counter8_async_resetb.v, simple_registers/counters/counter8_sync_reset/counter8_sync_reset.v
> 
> 
> 
> 
> 
>
> 
> 
This PR improves in the following aspects: 
- Add initial condition to counter designs, without which yosys cannot set initial values in simulations
> 
> - [x] RTL …
=> [HDL] Add initial condition to counter designs

simple_registers/counters/counter16/Makefile, simple_registers/counters/counter16/counter16.v, simple_registers/counters/counter16/test_counter16.py
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL
> - [x] Regression tests
> - [x] Continous Integration (CI) scripts …
=> Adding Counter16 Benchmark in microbenchmarks

README.md, docs/source/developer/naming_convention.rst, docs/source/index.rst
> - [x] To address an existing issue. If so, please provide a link to the issue: #10 
> 
> 
Currently, the project has the following limitations:
- no link to online documentation in the project README.md
>
> 
> 
This PR improves in the following aspects:
> 
> - [ ] RTL
> - [x] Documentation
> ### …
=> Add documentation link to README.md

docs/source/developer/version_number.rst
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL
> - [x] Documentation …
=> [Doc] Typo

simple_registers/counters/counterdown16_1clk_posedge_async_resetn/test_counterdown16_1clk_posedge_async_resetn.py, simple_registers/counters/counterdown16_1clk_posedge_async_resetp/test_counterdown16_1clk_posedge_async_resetp.py, simple_registers/counters/counterdown16_1clk_posedge_sync_resetn/test_counterdown16_1clk_posedge_sync_resetn.py, simple_registers/counters/counterdown16_4clk_posedge_async_resetn/test_counterdown16_4clk_posedge_async_resetn.py, simple_registers/counters/counterup16_1clk_posedge_async_resetn/test_counterup16_1clk_posedge_async_resetn.py, simple_registers/counters/counterup16_1clk_posedge_async_resetp/test_counterup16_1clk_posedge_async_resetp.py, simple_registers/counters/counterup16_1clk_posedge_sync_resetn/test_counterup16_1clk_posedge_sync_resetn.py, simple_registers/counters/counterup16_4clk_posedge_async_resetn/test_counterup16_4clk_posedge_async_resetn.py
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL …
=> Set Tab to 2 Spaces for Counter16 Cocotb Tests

simple_registers/counters/counterdown16_1clk_negedge_async_resetp/Makefile, simple_registers/counters/counterdown16_1clk_negedge_async_resetp/counterdown16_1clk_negedge_async_resetp.v, simple_registers/counters/counterdown16_1clk_negedge_async_resetp/test_counterdown16_1clk_negedge_async_resetp.py, simple_registers/ff/dffnr/Makefile, simple_registers/ff/dffnr/dffnr.v, simple_registers/ff/dffnr/test_dffnr.py, simple_registers/rtl_list.yaml
> Behavioral model and cocotb test case of neg-edge triggered D flip flop and neg-edge triggered 16 bit down counter have been added. These benchmark shall be added. 
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL
> - [ ] …
=> adding benchmark to test negedge flip-flops

docs/requirements.txt
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL …
=> Fix doc build errors by removing out-of-date packages

simple_registers/counters/counterdown16_1clk_posedge_async_resetn/Makefile
Optionally add VCS support to run tests on both FPGA-level and Unit-level. Make sure to override the SIM=modelsim option with SIM=vcs under dv makefile: https://github.com/RapidFlex/alkaid_efpga/blob/2144f6b980e807a6677c8bf27118496ebc5ac6fc/dv/Makefile#L11
> 
> 
> 
> 
> 
> 
> - [ ] RTL
> - [ ] Timing …
=> Update Makefile to Support VCS Optionally

simple_gates/adder/adder_16/Makefile, simple_gates/adder/adder_4/Makefile, simple_gates/adder/adder_6/Makefile, simple_gates/adder/adder_8/Makefile, simple_gates/and2/Makefile, simple_gates/and2_latch/Makefile, simple_gates/and2_latch_2clock/Makefile, simple_gates/and2_or2/Makefile, simple_gates/and2_pipelined/Makefile, simple_gates/and4/Makefile, simple_gates/or2/Makefile, simple_registers/counters/counterdown16_1clk_negedge_async_resetp/Makefile, simple_registers/counters/counterdown16_1clk_posedge_async_resetn/Makefile, simple_registers/counters/counterdown16_1clk_posedge_async_resetp/Makefile, simple_registers/counters/counterdown16_1clk_posedge_sync_resetn/Makefile, simple_registers/counters/counterdown16_4clk_posedge_async_resetn/Makefile, simple_registers/counters/counterup16_1clk_posedge_async_resetn/Makefile, simple_registers/counters/counterup16_1clk_posedge_async_resetp/Makefile, simple_registers/counters/counterup16_1clk_posedge_sync_resetn/Makefile, simple_registers/counters/counterup16_4clk_posedge_async_resetn/Makefile, simple_registers/ff/dffnr/Makefile
Refer this PR to see details: https://github.com/tangxifan/micro_benchmark/pull/29
> 
> 
> 
> 
> 
> 
> - [ ] RTL …
=> Update all Makefiles to support VCS Optionally

simple_registers/counters/counterupn_1clk_dualedge_async_resetp/Makefile, simple_registers/counters/counterupn_1clk_dualedge_async_resetp/counterupn_1clk_dualedge_async_resetp.v, simple_registers/counters/counterupn_1clk_dualedge_async_resetp/test_counterupn_1clk_dualedge_async_resetp.py
Dual edge Scale able Up Counter with Asynchronous Reset 
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL
> - [] Design Verification
> - [ ] Require a change on Quality of Results …
=> Add Scalable Dual-edge up counter

simple_registers/counters/counterup32_1clk_async_reset_n_instances/Makefile, simple_registers/counters/counterup32_1clk_async_reset_n_instances/counterup32_1clk_async_reset_n_instances.v, simple_registers/counters/counterup32_1clk_async_reset_n_instances/test_counterup32_1clk_async_reset_n_instances.py
32 bit up counter with async reset instantiated multiple times for maximum utilization of CLB's 
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [] RTL
> - [ ] …
=> new benchmark: maximum utilization of CLBS

simple_registers/counters/counterup36_8_2clk_async_resetp/Makefile, simple_registers/counters/counterup36_8_2clk_async_resetp/counterup12_1clk_async_resetp.v, simple_registers/counters/counterup36_8_2clk_async_resetp/counterup16_1clk_async_resetp.v, simple_registers/counters/counterup36_8_2clk_async_resetp/counterup36_8_2clk_async_resetp.v, simple_registers/counters/counterup36_8_2clk_async_resetp/counterup8_1clk_async_resetp.v, simple_registers/counters/counterup36_8_2clk_async_resetp/test_counterup36_8_2clk_async_resetp.py
8 12 and 16 bit counters instantiated and mapped on multiple IOs for testing of maximum IOs.
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL
> - [ ] …
=> Maximum IO (2784) CHECK

simple_registers/rtl_list.yaml
> 
> 
> 
> 
> 
>
> 
> 
This PR improves in the following aspects:
> 
> - [ ] RTL
> - [ ] Break …
=> [test] deploy newly added benchmarks to regression tests

fsm/scalable_seq_detector/Makefile
updated make file. This will be used for DV flow.
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL
> - …
=> update in make file

simple_registers/counters/counterup36_8_2clk_async_resetp/Makefile, simple_registers/counters/counterup36_8_2clk_async_resetp/counterup10_1clk_async_resetp.v, simple_registers/counters/counterup36_8_2clk_async_resetp/counterup36_8_2clk_async_resetp.v, simple_registers/counters/counterup36_8_2clk_async_resetp/test_counterup36_8_2clk_async_resetp.py, utils/tasks/simple_registers_rtl_list.yaml
changes for testing updated IOs (2784)
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL
> - [ ] Break …
=> updates for maximum IOs

fsm/fsm_seq_detector/Makefile, fsm/fsm_seq_detector/fsm_seq_detector.v, fsm/fsm_seq_detector/test_fsm_seq_detector.py, utils/tasks/fsm_rtl_list.yaml
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [x] RTL
> - [x] Regression tests …
=> adding finite state sequence detector

fsm/scalable_seq_detector/scalable_seq_detector.v, fsm/scalable_seq_detector/test_scalable_seq_detector.py
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL …
=> fixing reset de-asssert at active-edge problem

simple_registers/counters/counterup16_7clk_posedge_async_resetn/Makefile, simple_registers/counters/counterup16_7clk_posedge_async_resetn/counterup16.v, simple_registers/counters/counterup16_7clk_posedge_async_resetn/counterup16_7clk_posedge_async_resetn.v, simple_registers/counters/counterup16_7clk_posedge_async_resetn/test_counterup16_7clk_posedge_async_resetn.py, utils/tasks/simple_registers_rtl_list.yaml
> 
> 
> 
> 
> 
>counterup16_7clk_posedge_async_resetn  16 bit counter instantiated using 7 clocks
> 
> 
> 
> 
> 
> 
> - [ ] RTL
> - [ ] Require a change …
=> counter16 using 7 clocks

simple_registers/counters/counterup16_8clk_posedge_async_resetn/Makefile, simple_registers/counters/counterup16_8clk_posedge_async_resetn/counterup16.v, simple_registers/counters/counterup16_8clk_posedge_async_resetn/counterup16_8clk_posedge_async_resetn.v, simple_registers/counters/counterup16_8clk_posedge_async_resetn/test_counterup16_8clk_posedge_async_resetn.py, utils/tasks/simple_registers_rtl_list.yaml
> 
> 
> 
> 
> 
>16 bit up counter instantiated multiple times using 8 different clocks
> 
> 
> 
> 
> 
> 
> - [ ] RTL
> - [ ] Require a change on Quality …
=> updated design: 8 clocks

simple_registers/counters/counterup36_8_2clk_async_resetp/test_counterup36_8_2clk_async_resetp.py
> 
> 
> 
> 
> 
>updated test bench 
> 
> 
> 
> 
> 
> 
> - [ ] RTL
> - [ ] Break back-compatibility. …
=> updated testbench

docs/source/developer/contributor_guidelines.rst
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL …
=> [doc] add documentation guidelines

simple_registers/clk_divider/clk_divider.v
> - [X] Breaking new feature. If so, please describe details in the description part.
> 
> 
> 
> 
> 
>
> Modified the clk_divider rtl based on vpr issues.
> 
> 
> 
> 
> 
> 
> - [X] RTL
> …
=> clk_divider design updated based on vpr issues

simple_registers/clk_divider/clk_divider.v, simple_registers/clk_divider/test_clk_divider.py, simple_registers/pwm_generator/pwm_generator.v, simple_registers/pwm_generator/test_pwm_generator.py
> pwm_generator and clk_divider designs are modified to remove double reset.
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [x] RTL
> - [ ] Require a change on …
=> Design modified to remove double reset

.github/labeler.yml, .github/workflows/install_dependencies_vexriscv_ubuntu22p04.sh, .github/workflows/update_vexriscv.yml, Makefile
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL …
=> VexRiscV auto-updater

.github/labeler.yml, .github/workflows/patch_updater.yml, .github/workflows/update_vexriscv.yml
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL …
=> Disable Version auto-bot; Fixed a bug in VexRiscV autobot

.github/workflows/update_external_benchmark.yml, Makefile
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL …
=> [script] add verilog-spi auto-update

.github/workflows/update_external_benchmark.yml
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL …
=> Fixed a bug where empty commit will not be made on CI for external benchmark

.github/workflows/update_external_benchmark.yml, Makefile
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL …
=> [script] add auto-updator for dsp filter and cordic

Makefile
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL …
=> [script] typo

interface/opencores_spi/rtl/spi_master.v, interface/opencores_spi/rtl/spi_slave.v, interface/opencores_spi/testbench/TB_SPI_MasSlv.v
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL …
=> [benchmark] add spi from opencores

simple_gates/adder/adder_16/Makefile, simple_gates/adder/adder_4/Makefile, simple_gates/adder/adder_6/Makefile, simple_gates/adder/adder_8/Makefile
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] RTL …
=> [script] simplify makefile
